use BuildWiseDB;
INSERT INTO Specialization (name)
VALUES
("Civil and Industrial Construction"),
("Infrastructure and Public Works"),
("Building Installations"),
("Construction Materials"),
("Architecture, Design, and Consulting"),
("Demolition and Excavation"),
("Rehabilitation and Renovation"),
("Green and Sustainable Construction"),
("Maintenance and Repairs"),
("Project Management"),
("Health and Safety"),
("Quality Control"),
("Surveying and Geomatics"),
("Electrical Installations"),
("Mechanical Installations"),
("Plumbing and Sanitary Installations"),
("HVAC Systems"),
("Fire Protection Systems"),
("Interior Design"),
("Landscaping"),
("Urban Planning"),
("Environmental Engineering"),
("Structural Engineering"),
("Geotechnical Engineering"),
("Transportation Engineering"),
("Water Resources Engineering"),
("Construction Management"),
("Facility Management");